# Generated by Django 3.2.5 on 2021-07-15 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.FloatField(default=0, verbose_name='price')),
                ('short_name', models.CharField(max_length=50, verbose_name='short name')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='logo')),
                ('reserve', models.FloatField(verbose_name='reserve')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency', verbose_name='currency')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xchange_pair', to='main.currency', verbose_name='pair')),
            ],
        ),
    ]
