# Generated by Django 3.2.5 on 2021-07-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet_address', models.CharField(max_length=50, verbose_name='btc wallet address')),
                ('eth_wallet_address', models.CharField(max_length=50, verbose_name='eth wallet address')),
                ('usd_wallet_address', models.CharField(max_length=50, verbose_name='usd wallet address')),
                ('account_number', models.CharField(max_length=50, verbose_name='bank account number')),
                ('account_name', models.CharField(blank=True, max_length=50, verbose_name='bank account name')),
                ('bank', models.CharField(max_length=50, verbose_name='bank')),
                ('account_type', models.CharField(max_length=50, verbose_name='account type')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('short_name', models.CharField(max_length=50, verbose_name='short name')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='logo')),
                ('reserve', models.FloatField(verbose_name='reserve')),
                ('min_price', models.CharField(default=1, max_length=50, verbose_name='min to buy')),
                ('max_price', models.CharField(default=10, max_length=50, verbose_name='max to buy')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_equivalent', models.FloatField(default=10, help_text='x number of currency, gives how much of its pair ?', verbose_name='currency_rate')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.currency', verbose_name='currency')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xchange_pair', to='main.currency', verbose_name='pair')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('review', models.CharField(max_length=50, verbose_name='review')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.FloatField(verbose_name='currency price')),
                ('pair_amount', models.FloatField(verbose_name='pair price')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('transaction_hash', models.CharField(max_length=24, verbose_name='transaction hash')),
                ('has_paid', models.BooleanField(default=False, verbose_name='paid')),
                ('has_mark_paid', models.BooleanField(default=False, verbose_name='mark paid')),
                ('wallet_address', models.CharField(blank=True, max_length=50, verbose_name='wallet')),
                ('account_name', models.CharField(blank=True, max_length=50, verbose_name='account name')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='account number')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='account type')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='bank name')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='fullname')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='surname')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='phone')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exchangepair', verbose_name='pair')),
            ],
        ),
    ]
