# Generated by Django 3.2.5 on 2021-08-16 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='surname',
        ),
    ]
