# Generated by Django 3.2.5 on 2021-07-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepair',
            name='rate',
            field=models.CharField(max_length=50, verbose_name='rate'),
        ),
    ]
