# Generated by Django 3.2.5 on 2021-07-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_exchangepair_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet_address', models.CharField(max_length=50, verbose_name='btc wallet address')),
                ('eth_wallet_address', models.CharField(max_length=50, verbose_name='eth wallet address')),
                ('usd_wallet_address', models.CharField(max_length=50, verbose_name='usd wallet address')),
                ('account_no', models.CharField(max_length=50, verbose_name='bank account number')),
                ('bank', models.CharField(max_length=50, verbose_name='bank')),
                ('account_type', models.CharField(max_length=50, verbose_name='account type')),
            ],
        ),
    ]
