# Generated by Django 3.2.5 on 2021-07-16 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='max_price',
            field=models.CharField(default=10, max_length=50, verbose_name='max to buy'),
        ),
        migrations.AddField(
            model_name='currency',
            name='min_price',
            field=models.CharField(default=1, max_length=50, verbose_name='min to buy'),
        ),
    ]
