# Generated by Django 3.2.5 on 2021-07-17 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210716_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('body', models.TextField(verbose_name='body')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('review', models.CharField(max_length=50, verbose_name='review')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.FloatField(verbose_name='currency price')),
                ('pair_amount', models.FloatField(verbose_name='pair price')),
                ('timestamp', models.FloatField(verbose_name='timestamp')),
                ('translation_hash', models.CharField(max_length=24, verbose_name='transaction hash')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exchangepair', verbose_name='exchange')),
            ],
            options={
                'verbose_name_plural': 'Transaction Histories',
            },
        ),
    ]
