# Generated by Django 3.2.5 on 2021-07-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_news_review_transactionhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangepair',
            name='rate',
        ),
        migrations.AddField(
            model_name='exchangepair',
            name='pair_equivalent',
            field=models.FloatField(default=0, help_text='x number of currency, gives how much of its pair ?', verbose_name='currency_rate'),
        ),
    ]
