# Generated by Django 3.2.5 on 2021-07-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_exchangepair_pair_equivalent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepair',
            name='pair_equivalent',
            field=models.DecimalField(decimal_places=8, default=10, help_text='x number of currency, gives how much of this pair ?', max_digits=19, verbose_name='currency_rate'),
        ),
    ]
