# Generated by Django 3.2.5 on 2021-07-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_currency_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_amount', models.FloatField(verbose_name='currency price')),
                ('pair_amount', models.FloatField(verbose_name='pair price')),
                ('timestamp', models.FloatField(verbose_name='timestamp')),
                ('translation_hash', models.CharField(max_length=24, verbose_name='transaction hash')),
                ('has_paid', models.BooleanField(verbose_name='paid')),
                ('wallet_address', models.CharField(blank=True, max_length=50, verbose_name='wallet')),
                ('account_name', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('account_type', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('fullname', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('email', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='bank')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.exchangepair', verbose_name='pair')),
            ],
        ),
    ]
