# Generated by Django 3.2.5 on 2021-07-17 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_transaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='translation_hash',
            new_name='transaction_hash',
        ),
    ]
