# Generated by Django 3.2.5 on 2021-07-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210717_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='account_no',
            new_name='account_number',
        ),
        migrations.AddField(
            model_name='config',
            name='account_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank account number'),
        ),
    ]
