# Generated by Django 3.2.5 on 2021-07-17 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210717_1759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='mark_paid',
            new_name='has_mark_paid',
        ),
        migrations.AlterField(
            model_name='config',
            name='account_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank account name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='account type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='surname',
            field=models.CharField(blank=True, max_length=50, verbose_name='surname'),
        ),
    ]
