# Generated by Django 3.2.5 on 2021-07-17 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210717_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionHistory',
        ),
    ]
